apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: app-html
spec:
  revisionHistoryLimit: 0 
  replicas: 0
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html
        image: lteixeira93/app-html:1.2
        ports:
        - containerPort: 80
