apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: vote
spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379 # Redis port
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
        - name: redis-data
          emptyDir: {}         
  selector:
    matchLabels:
      app: redis
  replicas: 1
    
    